### ISSUE TITLE
v1.2.0

### ISSUE THREAD

**Issue by kamocat** [kamocat/QCX-SSB#5]
I'm considering features for a new revision. Here's what I've come up with so far:

- Test points
    - Power rails
    - Clock outputs of si5351
    - Inputs and outputs of op-amps
    - ADC inputs, DAC output
    - Band-pass filter
- Rewire mux for binary decoding (rather than graycode decoding), to remove need for phase offsets in si5351
- Indicator LEDs (using extra pins from the uC)
- Put OLED on a different I2C bus.
    (This requires upgrading to the 48-pin package)
- Select a new buck regulator that's available internationally

**Comment by kamocat** [comment]
Our analog front-end is missing a few features:
- Low-pass filtering after the quadrature sampling to prevent aliasing. (Since our input bandwidth is 500kHz this requirement is pretty relaxed, but we could set the corner at 5Khz and get 10dB of out-of-band attenuation
- Clipping circuit to prevent damage to the ADC. With the op-amps supplied with 12v, they can provide well over the 3.3v swing the ADC can accommodate. A zener diode would do the job.

**Comment by howard0su** [comment]
Rewire mux for binary decoding (rather than graycode decoding), to remove need for phase offsets in si5351
^^^^ do you mean that we will have one channel ADC used, and do the decouple IQ inside STM32?

Select a new buck regulator that's available internationally
^^^ Can we just use 7805 and down to 3.3 via diode? DC/DC may introduce noise. not sure if it is worth.

**Comment by howard0su** [comment]
I also suggest add one additional LNA and one Att in front of ADC

**Comment by kamocat** [comment]
> Rewire mux for binary decoding (rather than graycode decoding), to remove need for phase offsets in si5351
> ^^^^ do you mean that we will have one channel ADC used, and do the decouple IQ inside STM32?

No. Currently we're generating the carrier frequency on output 1 and 2 of the si5351, with a 90 degree offset. However, the offset configuration has limited accuracy. Instead, we could generate it at twice the frequency, and connect the outputs of the mux in a different order. This eliminates any clock phase error in our I/Q sampling and makes the clock easier to configure.

> Select a new buck regulator that's available internationally
> ^^^ Can we just use 7805 and down to 3.3 via diode? DC/DC may introduce noise. not sure if it is worth.

I think the buck regulator is worth trying, since it decreases RX power consumption by 60%. I was very careful in my layout to keep the regulator away from sensitive signals. I think the digital noise from the micro-controller will have more impact, not to mention the voltage doubler in the OLED. My goal is to eliminate the 5v rail entirely - I haven't yet because of the 74ACT00.

>I also suggest add one additional LNA and one Att in front of ADC

I've been wondering about how to do this. Do you have a part or configuration in mind? A variable attenuation would be really nice.
